apiVersion: 1

prune: true
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1
    jsonData:
      httpMethod: POST
      timeInterval: 30s
      prometheusType: Prometheus
      prometheusVersion: 3.15.0
